# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: corepack
        run: corepack enable

      - name: yarn global
        run: corepack prepare yarn@stable --activate

      - name: Set yarn version
        run: yarn set version stable

      - name: install
        working-directory: .
        run: yarn install

      - name: build
        working-directory: .
        run: yarn run build